GET  http://localhost:3001/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT3RpbSBCcmlhbiIsImVtYWlsIjoib3RpbXMuYnJpYW5AZ21haWwuY29tIiwiaWQiOiI2NWE5NzEzN2FiYjI0NjY4ZmZkMzQ2YWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDU2MDM0NTMsImV4cCI6MTcwNTYwNzA1M30.yExG7latuDb9_NJXVsE9o4AB4-lcpR2KDC6-zJ9eE44