GET http://localhost:3001/api/employees/65a97137abb24668ffd346af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT3RpbSBCcmlhbiIsImVtYWlsIjoib3RpbXMuYnJpYW5AZ21haWwuY29tIiwiaWQiOiI2NWE5NzEzN2FiYjI0NjY4ZmZkMzQ2YWYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDY0OTQyNDUsImV4cCI6MTcwNjQ5Nzg0NX0.CB2-OkqXzvEWY_5UEEAT3_OfzBnTLosdyHXZLoC94YQ